# frozen_string_literal: true

module Chemicalml
  module Cml
    # Shared attribute + xml-mapping declarations for every CML element.
    #
    # Each module here is mixed into the corresponding `Schema3::*` and
    # `Schema24::*` wire class. Schema-version-specific deviations live
    # in `Base::Schema3Only::*` / `Base::Schema24Only::*` and are
    # included only by the relevant version's classes — keeping the
    # shared declarations open for extension, closed for modification.
    module Base
      autoload :Array,            "chemicalml/cml/base/array"
      autoload :Atom,             "chemicalml/cml/base/atom"
      autoload :AtomArray,        "chemicalml/cml/base/atom_array"
      autoload :AtomParity,       "chemicalml/cml/base/atom_parity"
      autoload :Bond,             "chemicalml/cml/base/bond"
      autoload :BondArray,        "chemicalml/cml/base/bond_array"
      autoload :BondStereo,       "chemicalml/cml/base/bond_stereo"
      autoload :Dictionary,       "chemicalml/cml/base/dictionary"
      autoload :DictionaryEntry,  "chemicalml/cml/base/dictionary_entry"
      autoload :Document,         "chemicalml/cml/base/document"
      autoload :Formula,          "chemicalml/cml/base/formula"
      autoload :Identifier,       "chemicalml/cml/base/identifier"
      autoload :Label,            "chemicalml/cml/base/label"
      autoload :List,             "chemicalml/cml/base/list"
      autoload :Matrix,           "chemicalml/cml/base/matrix"
      autoload :Metadata,         "chemicalml/cml/base/metadata"
      autoload :MetadataList,     "chemicalml/cml/base/metadata_list"
      autoload :Module,           "chemicalml/cml/base/cml_module"
      autoload :Molecule,         "chemicalml/cml/base/molecule"
      autoload :Name,             "chemicalml/cml/base/name"
      autoload :Parameter,        "chemicalml/cml/base/parameter"
      autoload :ParameterList,    "chemicalml/cml/base/parameter_list"
      autoload :Product,          "chemicalml/cml/base/product"
      autoload :ProductList,      "chemicalml/cml/base/product_list"
      autoload :Property,         "chemicalml/cml/base/property"
      autoload :PropertyList,     "chemicalml/cml/base/property_list"
      autoload :Reaction,         "chemicalml/cml/base/reaction"
      autoload :ReactionList,     "chemicalml/cml/base/reaction_list"
      autoload :Reactant,         "chemicalml/cml/base/reactant"
      autoload :ReactantList,     "chemicalml/cml/base/reactant_list"
      autoload :Scalar,           "chemicalml/cml/base/scalar"
      autoload :Substance,        "chemicalml/cml/base/substance"
      autoload :Unit,             "chemicalml/cml/base/unit"
      autoload :UnitList,         "chemicalml/cml/base/unit_list"
      autoload :UnitType,         "chemicalml/cml/base/unit_type"
      autoload :UnitTypeList,     "chemicalml/cml/base/unit_type_list"
      autoload :Abundance, "chemicalml/cml/base/abundance"
      autoload :Action, "chemicalml/cml/base/action"
      autoload :ActionList, "chemicalml/cml/base/action_list"
      autoload :Amount, "chemicalml/cml/base/amount"
      autoload :Angle, "chemicalml/cml/base/angle"
      autoload :AnyCml, "chemicalml/cml/base/any_cml"
      autoload :ArrayList, "chemicalml/cml/base/array_list"
      autoload :AtomSet, "chemicalml/cml/base/atom_set"
      autoload :AtomType, "chemicalml/cml/base/atom_type"
      autoload :AtomTypeList, "chemicalml/cml/base/atom_type_list"
      autoload :AtomicBasisFunction, "chemicalml/cml/base/atomic_basis_function"
      autoload :Band, "chemicalml/cml/base/band"
      autoload :BandList, "chemicalml/cml/base/band_list"
      autoload :BasisSet, "chemicalml/cml/base/basis_set"
      autoload :BondSet, "chemicalml/cml/base/bond_set"
      autoload :BondType, "chemicalml/cml/base/bond_type"
      autoload :BondTypeList, "chemicalml/cml/base/bond_type_list"
      autoload :CellParameter, "chemicalml/cml/base/cell_parameter"
      autoload :ConditionList, "chemicalml/cml/base/condition_list"
      autoload :Crystal, "chemicalml/cml/base/crystal"
      autoload :Definition, "chemicalml/cml/base/definition"
      autoload :Description, "chemicalml/cml/base/description"
      autoload :Dimension, "chemicalml/cml/base/dimension"
      autoload :Documentation, "chemicalml/cml/base/documentation"
      autoload :Eigen, "chemicalml/cml/base/eigen"
      autoload :Electron, "chemicalml/cml/base/electron"
      autoload :Fragment, "chemicalml/cml/base/fragment"
      autoload :FragmentList, "chemicalml/cml/base/fragment_list"
      autoload :Gradient, "chemicalml/cml/base/gradient"
      autoload :Isotope, "chemicalml/cml/base/isotope"
      autoload :IsotopeList, "chemicalml/cml/base/isotope_list"
      autoload :Join, "chemicalml/cml/base/join"
      autoload :Kpoint, "chemicalml/cml/base/kpoint"
      autoload :KpointList, "chemicalml/cml/base/kpoint_list"
      autoload :Lattice, "chemicalml/cml/base/lattice"
      autoload :LatticeVector, "chemicalml/cml/base/lattice_vector"
      autoload :Length, "chemicalml/cml/base/length"
      autoload :Line3, "chemicalml/cml/base/line3"
      autoload :Link, "chemicalml/cml/base/link"
      autoload :Map, "chemicalml/cml/base/map"
      autoload :Mechanism, "chemicalml/cml/base/mechanism"
      autoload :MechanismComponent, "chemicalml/cml/base/mechanism_component"
      autoload :MoleculeList, "chemicalml/cml/base/molecule_list"
      autoload :Object, "chemicalml/cml/base/object"
      autoload :Observation, "chemicalml/cml/base/observation"
      autoload :Particle, "chemicalml/cml/base/particle"
      autoload :Peak, "chemicalml/cml/base/peak"
      autoload :PeakGroup, "chemicalml/cml/base/peak_group"
      autoload :PeakList, "chemicalml/cml/base/peak_list"
      autoload :PeakStructure, "chemicalml/cml/base/peak_structure"
      autoload :Plane3, "chemicalml/cml/base/plane3"
      autoload :Point3, "chemicalml/cml/base/point3"
      autoload :Potential, "chemicalml/cml/base/potential"
      autoload :PotentialForm, "chemicalml/cml/base/potential_form"
      autoload :PotentialList, "chemicalml/cml/base/potential_list"
      autoload :ReactionScheme, "chemicalml/cml/base/reaction_scheme"
      autoload :ReactionStep, "chemicalml/cml/base/reaction_step"
      autoload :ReactionStepList, "chemicalml/cml/base/reaction_step_list"
      autoload :ReactiveCentre, "chemicalml/cml/base/reactive_centre"
      autoload :Region, "chemicalml/cml/base/region"
      autoload :Sample, "chemicalml/cml/base/sample"
      autoload :Spectator, "chemicalml/cml/base/spectator"
      autoload :SpectatorList, "chemicalml/cml/base/spectator_list"
      autoload :Spectrum, "chemicalml/cml/base/spectrum"
      autoload :SpectrumData, "chemicalml/cml/base/spectrum_data"
      autoload :SpectrumList, "chemicalml/cml/base/spectrum_list"
      autoload :Sphere3, "chemicalml/cml/base/sphere3"
      autoload :Stmml, "chemicalml/cml/base/stmml"
      autoload :SubstanceList, "chemicalml/cml/base/substance_list"
      autoload :Symmetry, "chemicalml/cml/base/symmetry"
      autoload :System, "chemicalml/cml/base/system"
      autoload :Table, "chemicalml/cml/base/table"
      autoload :TableCell, "chemicalml/cml/base/table_cell"
      autoload :TableContent, "chemicalml/cml/base/table_content"
      autoload :TableHeader, "chemicalml/cml/base/table_header"
      autoload :TableHeaderCell, "chemicalml/cml/base/table_header_cell"
      autoload :TableRow, "chemicalml/cml/base/table_row"
      autoload :TableRowList, "chemicalml/cml/base/table_row_list"
      autoload :Torsion, "chemicalml/cml/base/torsion"
      autoload :Transform3, "chemicalml/cml/base/transform3"
      autoload :TransitionState, "chemicalml/cml/base/transition_state"
      autoload :Vector3, "chemicalml/cml/base/vector3"
      autoload :Xaxis, "chemicalml/cml/base/xaxis"
      autoload :Yaxis, "chemicalml/cml/base/yaxis"
      autoload :ZMatrix, "chemicalml/cml/base/z_matrix"
    end
  end
end
