# frozen_string_literal: true

module Chemicalml
  module Cml
    # Role marker modules — one per CML element. Included by every
    # schema-versioned wire class for that element (`Schema3::Molecule`
    # and `Schema24::Molecule` both `include Role::Molecule`).
    #
    # Constraints and translator rules check `node.is_a?(Role::Molecule)`
    # instead of `is_a?(Schema3::Molecule) || is_a?(Schema24::Molecule)`.
    # Adding Schema5 later requires zero constraint edits — Schema5's
    # classes just include the relevant Role modules.
    #
    # Each Role module is empty — it's a pure type marker, no methods.
    module Role
      autoload :Array,           'chemicalml/cml/role/array'
      autoload :Atom,            'chemicalml/cml/role/atom'
      autoload :AtomArray,       'chemicalml/cml/role/atom_array'
      autoload :AtomParity,      'chemicalml/cml/role/atom_parity'
      autoload :Bond,            'chemicalml/cml/role/bond'
      autoload :BondArray,       'chemicalml/cml/role/bond_array'
      autoload :BondStereo,      'chemicalml/cml/role/bond_stereo'
      autoload :Dictionary,      'chemicalml/cml/role/dictionary'
      autoload :DictionaryEntry, 'chemicalml/cml/role/dictionary_entry'
      autoload :Document,        'chemicalml/cml/role/document'
      autoload :Formula,         'chemicalml/cml/role/formula'
      autoload :Identifier,      'chemicalml/cml/role/identifier'
      autoload :Label,           'chemicalml/cml/role/label'
      autoload :List,            'chemicalml/cml/role/list'
      autoload :Matrix,          'chemicalml/cml/role/matrix'
      autoload :Metadata,        'chemicalml/cml/role/metadata'
      autoload :MetadataList,    'chemicalml/cml/role/metadata_list'
      autoload :Module,          'chemicalml/cml/role/cml_module'
      autoload :Molecule,        'chemicalml/cml/role/molecule'
      autoload :Name,            'chemicalml/cml/role/name'
      autoload :Parameter,       'chemicalml/cml/role/parameter'
      autoload :ParameterList,   'chemicalml/cml/role/parameter_list'
      autoload :Product,         'chemicalml/cml/role/product'
      autoload :ProductList,     'chemicalml/cml/role/product_list'
      autoload :Property,        'chemicalml/cml/role/property'
      autoload :PropertyList,    'chemicalml/cml/role/property_list'
      autoload :Reaction,        'chemicalml/cml/role/reaction'
      autoload :ReactionList,    'chemicalml/cml/role/reaction_list'
      autoload :Reactant,        'chemicalml/cml/role/reactant'
      autoload :ReactantList,    'chemicalml/cml/role/reactant_list'
      autoload :Scalar,          'chemicalml/cml/role/scalar'
      autoload :Substance,       'chemicalml/cml/role/substance'
      autoload :Unit,            'chemicalml/cml/role/unit'
      autoload :UnitList,        'chemicalml/cml/role/unit_list'
      autoload :UnitType,        'chemicalml/cml/role/unit_type'
      autoload :UnitTypeList,    'chemicalml/cml/role/unit_type_list'
      autoload :Abundance, 'chemicalml/cml/role/abundance'
      autoload :Action, 'chemicalml/cml/role/action'
      autoload :ActionList, 'chemicalml/cml/role/action_list'
      autoload :Amount, 'chemicalml/cml/role/amount'
      autoload :Angle, 'chemicalml/cml/role/angle'
      autoload :AnyCml, 'chemicalml/cml/role/any_cml'
      autoload :ArrayList, 'chemicalml/cml/role/array_list'
      autoload :AtomSet, 'chemicalml/cml/role/atom_set'
      autoload :AtomType, 'chemicalml/cml/role/atom_type'
      autoload :AtomTypeList, 'chemicalml/cml/role/atom_type_list'
      autoload :AtomicBasisFunction, 'chemicalml/cml/role/atomic_basis_function'
      autoload :Band, 'chemicalml/cml/role/band'
      autoload :BandList, 'chemicalml/cml/role/band_list'
      autoload :BasisSet, 'chemicalml/cml/role/basis_set'
      autoload :BondSet, 'chemicalml/cml/role/bond_set'
      autoload :BondType, 'chemicalml/cml/role/bond_type'
      autoload :BondTypeList, 'chemicalml/cml/role/bond_type_list'
      autoload :CellParameter, 'chemicalml/cml/role/cell_parameter'
      autoload :ConditionList, 'chemicalml/cml/role/condition_list'
      autoload :Crystal, 'chemicalml/cml/role/crystal'
      autoload :Definition, 'chemicalml/cml/role/definition'
      autoload :Description, 'chemicalml/cml/role/description'
      autoload :Dimension, 'chemicalml/cml/role/dimension'
      autoload :Documentation, 'chemicalml/cml/role/documentation'
      autoload :Eigen, 'chemicalml/cml/role/eigen'
      autoload :Electron, 'chemicalml/cml/role/electron'
      autoload :Fragment, 'chemicalml/cml/role/fragment'
      autoload :FragmentList, 'chemicalml/cml/role/fragment_list'
      autoload :Gradient, 'chemicalml/cml/role/gradient'
      autoload :Isotope, 'chemicalml/cml/role/isotope'
      autoload :IsotopeList, 'chemicalml/cml/role/isotope_list'
      autoload :Join, 'chemicalml/cml/role/join'
      autoload :Kpoint, 'chemicalml/cml/role/kpoint'
      autoload :KpointList, 'chemicalml/cml/role/kpoint_list'
      autoload :Lattice, 'chemicalml/cml/role/lattice'
      autoload :LatticeVector, 'chemicalml/cml/role/lattice_vector'
      autoload :Length, 'chemicalml/cml/role/length'
      autoload :Line3, 'chemicalml/cml/role/line3'
      autoload :Link, 'chemicalml/cml/role/link'
      autoload :Map, 'chemicalml/cml/role/map'
      autoload :Mechanism, 'chemicalml/cml/role/mechanism'
      autoload :MechanismComponent, 'chemicalml/cml/role/mechanism_component'
      autoload :MoleculeList, 'chemicalml/cml/role/molecule_list'
      autoload :Object, 'chemicalml/cml/role/object'
      autoload :Observation, 'chemicalml/cml/role/observation'
      autoload :Particle, 'chemicalml/cml/role/particle'
      autoload :Peak, 'chemicalml/cml/role/peak'
      autoload :PeakGroup, 'chemicalml/cml/role/peak_group'
      autoload :PeakList, 'chemicalml/cml/role/peak_list'
      autoload :PeakStructure, 'chemicalml/cml/role/peak_structure'
      autoload :Plane3, 'chemicalml/cml/role/plane3'
      autoload :Point3, 'chemicalml/cml/role/point3'
      autoload :Potential, 'chemicalml/cml/role/potential'
      autoload :PotentialForm, 'chemicalml/cml/role/potential_form'
      autoload :PotentialList, 'chemicalml/cml/role/potential_list'
      autoload :ReactionScheme, 'chemicalml/cml/role/reaction_scheme'
      autoload :ReactionStep, 'chemicalml/cml/role/reaction_step'
      autoload :ReactionStepList, 'chemicalml/cml/role/reaction_step_list'
      autoload :ReactiveCentre, 'chemicalml/cml/role/reactive_centre'
      autoload :Region, 'chemicalml/cml/role/region'
      autoload :Sample, 'chemicalml/cml/role/sample'
      autoload :Spectator, 'chemicalml/cml/role/spectator'
      autoload :SpectatorList, 'chemicalml/cml/role/spectator_list'
      autoload :Spectrum, 'chemicalml/cml/role/spectrum'
      autoload :SpectrumData, 'chemicalml/cml/role/spectrum_data'
      autoload :SpectrumList, 'chemicalml/cml/role/spectrum_list'
      autoload :Sphere3, 'chemicalml/cml/role/sphere3'
      autoload :Stmml, 'chemicalml/cml/role/stmml'
      autoload :SubstanceList, 'chemicalml/cml/role/substance_list'
      autoload :Symmetry, 'chemicalml/cml/role/symmetry'
      autoload :System, 'chemicalml/cml/role/system'
      autoload :Table, 'chemicalml/cml/role/table'
      autoload :TableCell, 'chemicalml/cml/role/table_cell'
      autoload :TableContent, 'chemicalml/cml/role/table_content'
      autoload :TableHeader, 'chemicalml/cml/role/table_header'
      autoload :TableHeaderCell, 'chemicalml/cml/role/table_header_cell'
      autoload :TableRow, 'chemicalml/cml/role/table_row'
      autoload :TableRowList, 'chemicalml/cml/role/table_row_list'
      autoload :Torsion, 'chemicalml/cml/role/torsion'
      autoload :Transform3, 'chemicalml/cml/role/transform3'
      autoload :TransitionState, 'chemicalml/cml/role/transition_state'
      autoload :Vector3, 'chemicalml/cml/role/vector3'
      autoload :Xaxis, 'chemicalml/cml/role/xaxis'
      autoload :Yaxis, 'chemicalml/cml/role/yaxis'
      autoload :ZMatrix, 'chemicalml/cml/role/z_matrix'
      autoload :Alternative, 'chemicalml/cml/role/alternative'
      autoload :Arg, 'chemicalml/cml/role/arg'
      autoload :ComplexObject, 'chemicalml/cml/role/complex_object'
      autoload :Expression, 'chemicalml/cml/role/expression'
      autoload :Float, 'chemicalml/cml/role/float'
      autoload :FloatArray, 'chemicalml/cml/role/float_array'
      autoload :Integer, 'chemicalml/cml/role/integer'
      autoload :IntegerArray, 'chemicalml/cml/role/integer_array'
      autoload :Operator, 'chemicalml/cml/role/operator'
      autoload :RelatedEntry, 'chemicalml/cml/role/related_entry'
      autoload :String, 'chemicalml/cml/role/string'
      autoload :StringArray, 'chemicalml/cml/role/string_array'
      autoload :Tcell, 'chemicalml/cml/role/tcell'
      autoload :Trow, 'chemicalml/cml/role/trow'
      autoload :Annotation, 'chemicalml/cml/role/annotation'
      autoload :Appinfo, 'chemicalml/cml/role/appinfo'
      autoload :Enumeration, 'chemicalml/cml/role/enumeration'
    end
  end
end
