require:
  - rubocop

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "pkg/**/*"
    - "vendor/**/*"
    - "coverage/**/*"
    - "reference-docs/**/*"
    - "spec/fixtures/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/Documentation:
  Enabled: false
